### ISSUE TITLE
Exception during import : The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine. : System.Data : 

### ISSUE THREAD

**Issue by rrd911** [MadAboutImport/DIFS#1]
I keep getting the following error:
Exception during import : The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine. : System.Data : 

I have searched Google and installed the recommended files but still get the same error. My system is as follows.

Office 2013 32bit
Windows 7 64bit

From the Logging Tab
SPImportHelper Information: 1000 : Progress : About to connect to source : 
SPImportHelper Information: 1023 : DataSetSource : Connection string Provider=Microsoft.ACE.OLEDB.12.0;Data Source=c:\all-032717.xlsx;Extended Properties="Excel
12.0 XML;HDR=YES;IMEX=0";
SPImportHelper Information: 1000 : Progress : Source connected : 
SPImportHelper Information: 1004 : DataSetSource : Fill select * from [jobs$]
SPImportHelper Information: 1000 : Progress : Exception during import : The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine. : System.Data :

**Comment by MadAboutImport** [comment]
This is not a problem with DIFS it simply means that the provider is not installed.  It is normally caused by using 64bit difs with a 32bit provider or vice versa.

**Comment by ghost** [comment]
I am seeing the same problem.  Tried on three different machines, one clean.  Any advice please?  the OLEDB 12.0 is registered on all three, so stumped!

**Comment by MadAboutImport** [comment]
Usually this means you are using 32bit DIFS with 64bit oledb drivers or vice versa.  Since it is probably easier to uninstall and re-install DIFS I would suggest you uninstall it and re-install at whichever version (32bit / 64bit) you are not using currently if that makes sense.
