### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by Titef** [MadAboutImport/DIFS#13]
Hello,

Can you confirm that we now must buy a license of the SPImport dll (http://www.ensentia.co.uk/spimport/) and that we can't have a free working version of your tool ?

Thanks

**Comment by gman8321** [comment]
Please confirm that the professional license is now needed. Trying to talk my boss into purchasing the professional version.

**Comment by kinsl4yer** [comment]
Same issue here. How can I proceed?
