### ISSUE TITLE
Logging using ScriptedImport.ps1

### ISSUE THREAD

**Issue by icemouseEj** [MadAboutImport/DIFS#2]
**Executing ScriptedImport.ps1 - see below -Script attached to Difs8beta3.zip, does not give any log as an output.
Can you advice how and where to specify the command to generate these logs?
Thanks.**

__Full_ path to your settings file_
$pathtosettings = "\\vmware-host\Shared Folders\Projects\ProductDevelopment\ImportForSharePoint\WorkingArea\Examples\Office365_StaffFolders_Folders_Excel_Select.xml"

__Full_ path to where SPImportHelper.DLL is deployed_
$pathtoassembly = "\\vmware-host\Shared Folders\Projects\ProductDevelopment\ImportForSharePoint\SourceCode\ImportForSharePoint\SPImportHelper\bin\Release";

_This loads the required assembliies_
_You may need to change the path if DIFS is not installed in this location_
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\SPImportHelper.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Runtime.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Publishing.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Taxonomy.dll") | Out-Null

_We_ create a new import settings object using an existing settings file_
$importsettings = [SPImportHelper.Settings.Utility]::LoadSettings($pathtosettings);

_We_ tell the user what source is being imported from_
Write-Host "Source : Connection String : " $importsettings.Source.OleDbSourceDataSetSettings.ConnectionString

_We_ Create a new import object_
$import = New-Object SPImportHelper.Import.DataSetImportToSharePoint_Console($importsettings);

_Write_ tell the user that we are starting the import_
Write-Host "Importing";

_We start the import_
$import.StartImport();

_Write tell the user that we have finished the import_
Write-Host "Finished";

**Comment by MadAboutImport** [comment]
This is covered in section 7.2 of the documentation DIFS.pdf.  It tells you how to enable logging.

**Comment by icemouseEj** [comment]
thanks for your fast reply,
but i try to configure difs.exe.xonfig in this way, but doesn't work when executing ScriptedImport.ps1.
This script works but it doesn't log into SPImportHelper.log
have i to configure something else?
Thanks.

**My DIFS.exe.config**

`<?xml version="1.0"?>
<configuration>
    <configSections>
    </configSections>
<startup>
  <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
</startup>
  <system.diagnostics>
    
    <trace autoflush="true"></trace>
    <sources>
      <source name="SPImportHelper">
        <listeners>
          
          <add name="eventlog"
              type="System.Diagnostics.TextWriterTraceListener"
              initializeData="C:\sviluppo\ImportForSharePoint\DIFS\SPImportHelper.log">
            
          </add>
        </listeners>
      </source>
    </sources>
  </system.diagnostics>
</configuration>`

**my ScriptedImport.ps1**
`$pathtoassembly = "C:\sviluppo\ImportForSharePoint\DIFS";

This loads the required assembliies
You may need to change the path if DIFS is not installed in this location
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\SPImportHelper.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Runtime.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Publishing.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Taxonomy.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\LogForDotNet.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.IdentityModel.dll") | Out-Null

Full path to your settings file
$pathToSettingsForLibrary = "C:\sviluppo\ImportForSharePoint\shpimport\Sales-Configuration-AM-Contracts.xml"

We create a new import settings object using an existing settings file
$ImportSettingsForLibrary = [SPImportHelper.Settings.Utility]::LoadSettings($pathToSettingsForLibrary);

We tell the user what source is being imported from
Write-Host "Source : Connection String : " $ImportSettingsForLibrary.Source.OleDbSourceDataSetSettings.ConnectionString

We Create a new import object
$import = New-Object SPImportHelper.Import.DataSetImportToSharePoint_Console($ImportSettingsForLibrary);

Write tell the user that we are starting the import
Write-Host "Importing AM-Contracts.xml";

We start the import
$import.StartImport();

Write tell the user that we have finished the import
Write-Host "Finished AM-Contracts.xml";`

**Comment by icemouseEj** [comment]
**my Sales -Configuration -AM -Contracts.xml**
-?xml version="1.0" encoding="utf -8"? -
 -DataSetImportSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema -instance" -
   -Source -
     -SourceDataSetType -OLEDbTable   -/SourceDataSetType -
     -OleDbSourceDataSetSettings -
       -ConnectionString -Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\sviluppo\111111111111.xlsx;Extended Properties="Excel 12.0 Xml;HDR=YES;IMEX=0";   -/ConnectionString -
       -/OleDbSourceDataSetSettings -
     -OleDbTableSourceDataSetSettings -
       -TableName -AMContracts$   -/TableName -
       -/OleDbTableSourceDataSetSettings -
     -OleDbSelectSourceDataSetSettings / -
     -ODBCSourceDataSetSettings / -
     -ODBCSelectSourceDataSetSettings / -
     -FileSystemFilesDataSetSettings / -
     -/Source -
   -Destination -
     -AuthenticationSettings -
       -AuthenticationType -Specified   -/AuthenticationType -
       -domain -111111111111   -/domain -
       -username -111111111111   -/username -
       -encryptedpassed -111111111111   -/encryptedpassed -
       -/AuthenticationSettings -
     -DestinationListSettings -
       -DestinationWebUrlRelative   -/sites/xxxxxxx/xxxxxxx   -/DestinationWebUrlRelative -
       -DestinationFolderUrlRelative   -/sites/xxxxxxx/xxxxxxx/AM Contracts   -/DestinationFolderUrlRelative -
       -DestinationServerUrl -xxxxxxx   -/DestinationServerUrl -
       -DestinationListName -AM Contracts   -/DestinationListName -
       -/DestinationListSettings -
     -DestinationItemSettings -
       -DestinationItemType -Document   -/DestinationItemType -
       -ItemExistsBehaviour -Overwrite   -/ItemExistsBehaviour -
       -ImportMappings -
         -ImportMapping xsi:type="ImportMapping_ManagedMetaDataCSOM" -
           -DestinationField -111111111111   -/DestinationField -
           -SourceColumn -111111111111   -/SourceColumn -
           -/ImportMapping -
         -/ImportMappings -
       -/DestinationItemSettings -
     -DestinationExecutionSettings -
       -PerItemImportThrottle -0   -/PerItemImportThrottle -
       -/DestinationExecutionSettings -
     -SourceColumns -
       -SourceFileNameAndPath -FullName   -/SourceFileNameAndPath -
       -ContentType -ContentType   -/ContentType -
       -DestinationSubFolder -DestinationSubDirectories   -/DestinationSubFolder -
       -DestinationFileName -DestinationFileName   -/DestinationFileName -
       -Publish -Publish   -/Publish -
       -CheckInComment -CheckInComment   -/CheckInComment -
       -PublishComment -Publish   -/PublishComment -
       -PageLayoutASPXName -PageLayoutASPXName   -/PageLayoutASPXName -
       -/SourceColumns -
     -/Destination -
   -/DataSetImportSettings -

**Comment by MadAboutImport** [comment]
I suspect that the difs.exe.config is ignored when you call the dll from Powershell.

 

Try [System.AppDomain]::CurrentDomain.SetData("APP_CONFIG_FILE", $config_path)

 

https://stackoverflow.com/questions/835862/powershell-calling-net-assembly-that-uses-app-config

 

 

If you want to troubleshoot your XML config file when best to do this through the DIFS user interface where logging is just a tick box.

 

Make sure you post any progress here for other users.

**Comment by icemouseEj** [comment]
I've put this line just below 
"[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Taxonomy.dll") | Out-Null"

In thi way.

**--- Part of MY ScriptImport.ps1---**
`$pathtoassembly = "C:\sviluppo\ImportForSharePoint\DIFS";
**$config_path = "C:\sviluppo\ImportForSharePoint\DIFS.exe.config";**

_This loads the required assembliies
You may need to change the path if DIFS is not installed in this location_
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\SPImportHelper.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Runtime.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Publishing.dll") | Out-Null
[System.Reflection.Assembly]::LoadFile($pathtoassembly+"\Microsoft.SharePoint.Client.Taxonomy.dll") | Out-Null
**[System.AppDomain]::CurrentDomain.SetData("APP_CONFIG_FILE", $config_path)`**


**But does not generate "SPImportHelper.log defined into difs.exe.config**

**--- Part of MY difs.exe.config---**

 - ?xml version="1.0"? - 
 - configuration - 
     - configSections - 
     - /configSections - 
 - startup - 
   - supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/ - 
 - /startup - 
   - system.diagnostics - 
     - !-- By setting autoflush false the listener will not be written to; this can get BIG.  Set to true for troubleshooting -- - 
     - trace autoflush="true" -  - /trace - 
     - sources - 
       - source name="SPImportHelper" - 
         - listeners - 
           - !-- The log file specified below will contain full details the of import.  The user running the import must have write permission and autoflush must be set to true.  If left in the default program files directory you must Run as Administrator -- - 
           - add name="eventlog"
              type="System.Diagnostics.TextWriterTraceListener"
              **initializeData="C:\sviluppo\ImportForSharePoint\DIFS\SPImportHelper.log" -** 
             - !--
             - filter type="System.Diagnostics.EventTypeFilter" initializeData="Information"/ - 
            -- - 
           - /add - 
         - /listeners - 
       - /source - 
     - /sources - 
   - /system.diagnostics - 
 - /configuration - 

What I'm doing wrong !!!

Thanks

**Comment by MadAboutImport** [comment]
Try Run as administrator?

**Comment by icemouseEj** [comment]
There's nothing to do. It Doesn't work also with administrator permission :(

**Comment by MadAboutImport** [comment]
Sorry to hear you could not get anywhere with this.  Next time and work on this I will take a better look.  All I can suggest before then is to perform any imports where you find you need logging (normally when you run in to problems) from the user interface and click the check box to log to UI.
