### ISSUE TITLE
Publish source code on github

### ISSUE THREAD

**Issue by tstojecki** [MadAboutImport/DIFS#3]
I am investigating this tool for my current project as it looks very promising. In the discussions I saw you mentioned that the source is installed with the installer. Any reason why you're not publishing source code directly on github? It would likely encourage contributions.

**Comment by dmdj** [comment]
Are there plans to get source code loaded here soon?  The tool does most of what we need for a project but we can't commit to using it without source.  We are also interested in contributing - specifically to add an Overwrite capability for Lists based on key columns.

**Comment by IgorMakar** [comment]
Yep ;) I would also like to change something regarding Lookup fields. We need for example multiple fields matching.

**Comment by MadAboutImport** [comment]
Can you be a bit more specific regarding multiple field matching?  Do you mean a lookup field that allows multiple values.

**Comment by IgorMakar** [comment]
sure ;)
I am talking about this: (_from xml configuration documentation_)
`<!-- This is the field in the lookup list the value of which matches the value in the source column-->         <LookupFieldInternalName>Title</LookupFieldInternalName> <!-- This is the CAML value type Text,Number,DateTime,Guid,MultiChoice,Lookup for the field on in the lookup list that matches the value specified in the source column -->         <LookupFieldCAMLType>Text</LookupFieldCAMLType> `

what if I want to find record in lookup list by 2 or more fields? This could often happen when you import multiple tables from relational database.

**Comment by MadAboutImport** [comment]
So your expectation is that the destination lookup field allows multiple values and you would want to configure the import to set multiple values against a single list item?

**Comment by IgorMakar** [comment]
no. I would like to find list item in lookup list by 'Product Name' AND 'Insurance Name' fields. Instead of just 'Title'.  
so your CAML query 
`string[] lookupFieldInternalName = new string[] { "<View><Query><Where><Eq><FieldRef Name='", importMapping_Lookup.LookupFieldInternalName, "' /><Value Type='", importMapping_Lookup.LookupFieldCAMLType, "'>", string_0, "</Value></Eq></Where></Query></View>" };` 
would contain `<And>` clause to combine multiple query conditions. 
`<Where><And><Eq>...</Eq><Eq>...</Eq></And></Where>`
Sorry for some disassembling ;)

**Comment by MadAboutImport** [comment]
Unfortunately SharePoint does not work that way.  The lookup is to a single field like ‘Title’ or ‘Product Code’.  You will need to do the pre-processing against the data source to turn your multiple fields into that single unique value I would guess.

**Comment by IgorMakar** [comment]
I believe it would work ;) I updated my previous post. As I see you just find that list item and return an ID of it.

**Comment by IgorMakar** [comment]
oh And I found 1 issue. 
the following code in SPImportHelper  
```
if (items.Count > 0)
{
  id = items[0].Id;
}

```
returns id of first found list item. I believe this behavior should be documented. Because it not obvious.

**Comment by tstojecki** [comment]
Closing as the question was about publishing the source code to github.
