### ISSUE TITLE
issue Opening Excel 

### ISSUE THREAD

**Issue by RonyZ13** [MadAboutImport/DIFS#4]
Hello,
i installed Microsoft Access Database Engine 2010 Redistributable 64 bit edition on my server. I am trying to import a large number of files with metadata from an excel sheet. However i am getting the folowing error:
SPImportHelper Information: 1000 : Progress : About to connect to source : 
SPImportHelper Information: 1023 : DataSetSource : Connection string Provider=Microsoft.ACE.OLEDB.12.0;Data Source="C:\CSV\source.xlsx";Extended Properties="Excel
12.0 Xml;HDR=YES;IMEX=0";
SPImportHelper Information: 1000 : Progress : Source connected : 
SPImportHelper Information: 1004 : DataSetSource : Fill select * from [files$]
SPImportHelper Information: 1000 : Progress : Exception during import : Pilote ISAM introuvable. : Microsoft Access Database Engine : 

Any help will be greatly appreciated. 
Rony

**Comment by MadAboutImport** [comment]
Make sure that if you have installed 64bit excel driver that you use 64bit difs

**Comment by RonyZ13** [comment]
Hi, 
i did i installed the 64bit difs. But still getting the same error. Any idea how i can solve this.
Regards

**Comment by MadAboutImport** [comment]
Try creating a user Dsn for the same connection to excel, you might get more helpful error message from the odbc config screen, also try different spreadsheet

**Comment by RonyZ13** [comment]
I created successfully  the DSN from ODBC 64 bit edition and no error message from the config screen.

**Comment by RonyZ13** [comment]
below is the content of my xml
<?xml version="1.0" encoding="utf-8"?>
<DataSetImportSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <Source>
 
 <SourceDataSetType>OLEDbSelect</SourceDataSetType>
 <OleDbSourceDataSetSettings>
 
 <ConnectionString>Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\_SCAN34\CSV\classeur1.xlsx;Extended Properties="Excel
12.0 Xml;HDR=YES;IMEX=0";</ConnectionString>
 </OleDbSourceDataSetSettings>
 <OleDbSelectSourceDataSetSettings>
 
 <SelectStatement>select * from [files$]</SelectStatement>
 </OleDbSelectSourceDataSetSettings>
 </Source>
 <Destination>
 
 <AuthenticationSettings>
 <AuthenticationType>Current</AuthenticationType>
 <domain/>
 <username/>
 <encryptedpassed/>
 </AuthenticationSettings>
 <DestinationItemSettings>
 
 <DestinationItemType>Document</DestinationItemType>
 
 <ItemExistsBehaviour>Overwrite</ItemExistsBehaviour>
 
 <ImportMappings>
 
  <ImportMapping xsi:type="ImportMapping_String">
 <DestinationField>Title</DestinationField>
 <SourceColumn>NOMFICHIER</SourceColumn>
 </ImportMapping>
 
 <ImportMapping xsi:type="ImportMapping_String">
 <DestinationField>Nom_client</DestinationField>
 <SourceColumn>CLINOM</SourceColumn>
 </ImportMapping>
 <ImportMapping xsi:type="ImportMapping_String">
 <DestinationField>Prenom_client</DestinationField>
 <SourceColumn>CLIPRENOM</SourceColumn>
 </ImportMapping>
  <ImportMapping xsi:type="ImportMapping_String">
 <DestinationField>Date_ordonnance</DestinationField>
 <SourceColumn>DATEORDO</SourceColumn>
 </ImportMapping>
   <ImportMapping xsi:type="ImportMapping_String">
 <DestinationField>Date_naissance</DestinationField>
 <SourceColumn>CLIANNIVERSAIRE</SourceColumn>
 </ImportMapping>
 </ImportMappings>
 </DestinationItemSettings>
 
 <DestinationListSettings>
 <DestinationWebUrlRelative>/</DestinationWebUrlRelative>
 <DestinationFolderUrlRelative>/Prescriptions</DestinationFolderUrlRelative>
 <DestinationServerUrl>http://intranet/</DestinationServerUrl>
 <DestinationListName>Prescriptions </DestinationListName>
 </DestinationListSettings>
 
 <SourceColumns>
 
 <SourceFileNameAndPath>PATH</SourceFileNameAndPath>
 
 <ContentType>Document</ContentType>
 
 
 <DestinationSubFolder/>
 
 <DestinationFileName>NOMFICHIER</DestinationFileName>
 </SourceColumns>
 </Destination>
</DataSetImportSettings>


Regards

**Comment by MadAboutImport** [comment]
Enable logging in the ui might be a more detailed error

**Comment by RonyZ13** [comment]
Thank you realy for your help and support. 
the log message i sent earlier was from the UI logging

**Comment by MadAboutImport** [comment]
Make sure your sheet name is files not sheet1 etc to match your select

**Comment by RonyZ13** [comment]
i made sure that the sheet name is "files" but still getting the same error.

**Comment by MadAboutImport** [comment]
https://support.microsoft.com/fr-fr/help/209805/you-receive-a-could-not-find-installable-isam-error-message-or-some-fi
