### ISSUE TITLE
Lookup on parent site

### ISSUE THREAD

**Issue by Titef** [MadAboutImport/DIFS#6]
Hello,

I didn't manage to make DIFS work when uploading items to a SharePoint list having a lookup field associated to a list which is not located in the same web but in a parent web.
From my understanding, DestinationListName and LookupListTitle must be in the same web which is not always the case...
Did I miss something in the configuration ?

Thanks!

**Comment by MadAboutImport** [comment]
Thanks.  This limitation will be addressed in a future release
