### ISSUE TITLE
Request URI Too Long

### ISSUE THREAD

**Issue by ghost** [MadAboutImport/DIFS#7]
I have successfully imported about 90% of an Excel list of files into SharePoint, however, there are a few that have an error such as this:

```
SPImportHelper Information: 1014 : Add_Document : Adding \\svr03\data$\NSML\18. Operations\Policies & Procedures\T&C Policies & Procedures\TC45-005 Proc for Client Instructions & Requests.doc to SharePoint as /Policies and Procedures/TC45-005 Proc for Client Instructions & Requests.pdf

SPImportHelper Information: 1000 : Progress : Exception importing : General : The remote server returned an error: (414) REQUEST URI TOO LONG.
```

I've tried removing the ampersands from the file names but that didn't seem to make any difference

**Comment by MadAboutImport** [comment]
SharePoint has a limit as to the max url length it is probably this

Also watch for special characters you can search for an explanation in Microsoft support

**Comment by ghost** [comment]
I've had other files in the same import going into the same library that had longer file names and they worked fine, such as this one:

```
SPImportHelper Information: 1014 : Add_Document : Adding \\svr03\data$\NSML\18. Operations\Policies & Procedures\T&C Policies & Procedures\TC11-015 Procedure for Adding and Excluding Beneficiaries.doc to SharePoint as /Policies and Procedures/TC11-015 Procedure for Adding and Excluding Beneficiaries.pdf
```

Main difference I can see is the ampersand in the file name, but I've tried removing that from the file name and any meta-data but I still get the same error message

**Comment by MadAboutImport** [comment]
It is not just the file name that is the problem it is the full path length

**Comment by ghost** [comment]
They're all coming from the same path into the same document library though, so ones with longer full paths are working. For example:

This one works:
> \\\svr03\data$\NSML\18. Operations\Policies & Procedures\T&C Policies & Procedures\TC35-018e External Accounts Review Form (audited or listed entities).pdf

> /policies and procedures/TC35-018e External Accounts Review Form (audited or listed entities).pdf

Whereas this one which is shorter doesn't work:

> \\\svr03\data$\NSML\18.   Operations\Policies & Procedures\T&C Policies &   Procedures\TC42-006 Proc Selec appt and rev ass man.DOC

> /policies and procedures/TC42-006 Proc Selec appt and rev ass man.DOC

**Comment by MadAboutImport** [comment]
Try uploading manually you might get a more meaningful message

**Comment by ghost** [comment]
In the end it did come down to ampersands, I had removed them from the filenames but there were some in other bits of metadata. They uploaded fine once I removed all traces of ampersands from the filenames and metadata.
