### ISSUE TITLE
Unsupported SharePoint version 15.0.4905.1000

### ISSUE THREAD

**Issue by CanSophMatt** [MadAboutImport/DIFS#8]
I'm using the 64 bit version of DIFS 2.9. Everything has been working for me up until now. I'm receiving the following error message...

Source filled : 1 rows loaded
About to connect to destination : 
Exception during import : Unsupported SharePoint version 15.0.4905.1000.  Please download an updated SPImportHelper.DLL from http://hyperurl.co/tqcr4e  : SPImportHelper : 

Any suggestions on how to resolve this?

**Comment by MadAboutImport** [comment]
One of the assemblies I use for accessing SharePoint is a freeware product and times out from time to time.  I’ll update the build when I get a chance.  In the meantime just download the assembly from the link and overwrite that of the same name in the DIFS folder.

**Comment by CanSophMatt** [comment]
Thank you, that fixed the issue

**Comment by Funies** [comment]
Hi,

I am new to this and I am getting the same error message.

Exception during import : Unsupported SharePoint version 15.0.4763.1000.  Please download an updated SPImportHelper.DLL from http://hyperurl.co/tqcr4e  : 

How do I resolve it?
