### ISSUE TITLE
Unsupported SharePoint version 16.0.7213.1207 & SPImportHelper.dll

### ISSUE THREAD

**Issue by DIFSUser** [MadAboutImport/DIFS#9]
I'm getting the following error message:
Exception during import : Unsupported SharePoint version 16.0.7213.1207. Please download an updated SPImportHelper.DLL from http://hyperurl.co/tqcr4e : SPImportHelper :

The link to download SPImportHelper.dll doesn't work for me.    I'm getting a "page can't be displayed" message when trying to access "http://hyperurl.co/tqcr4e" from the browser.   What am I doing wrong?
Thanks.

**Comment by MadAboutImport** [comment]
I’m guessing you are behind a firewall or proxy that is blocking the url.

**Comment by DIFSUser** [comment]
Thanks!  That was exactly the source of the problem.

**Comment by kenflorian** [comment]
This url http://hyperurl.co/tqcr4e now routes back to your main download page for the free or paid version. I'm ready to pay for the full version as soon as I know I can get it running in my environment.

**Comment by nichuet** [comment]
I have the same remark as @kenflorian : I'm ready to pay for the .dll but I want to be sure that it works with it.
The message that I have : _"Unsupported SharePoint version 16.0.7813.1204.  Please download an updated SPImportHelper.DLL from http://hyperurl.co/tqcr4e"_

**Comment by MadAboutImport** [comment]
I can only speak for myself but I’ve bought the pro version for customer projects and its worked perfectly.

**Comment by niftyc** [comment]
I also have the same comment as @kenflorian and @nichuet .
How can I test this solution without being able to download an updated SPImportHelper assembly?
My client requires updates to SP lists performed nightly from a source containing several CSV files.
